name: Black Code Fromatter

on: [push, pull_request]

jobs:
    black:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'
            - name: Install pre-commit
              run: pip install pre-commit
            - name: Run pre-commit (Black)
              run: pre-commit run --all-files --hook-stage manual